export const PLANS = {
  free: {
    id: "free",
    name: "Free Sandbox",
    shortName: "Free",
    badge: "FREE TIER",
    badgeClass: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700",
    storageTotalGB: 15.0,
    storageUsedGB: 1.2,
    storageUsedPercentage: 8,
    maxVideoQuality: "720p HLS",
    allowedVideoQualities: ["720p", "480p"],
    bedrockMonthlyDocs: 50,
    bedrockTokensTotal: 50000,
    bedrockTokensUsed: 4200,
    rekognitionMonthlyScans: 500,
    rekognitionScansUsed: 124,
    fargateComputeMonthlyMins: 30,
    fargateComputeUsedMins: 18,
    isEnterprise: false,
    infraTitle: "Shared AWS Serverless Multi-Tenant",
    infraDesc: "Standard serverless media ingestion with TLS 1.3 encryption and automated moderation gate.",
  },
  pro: {
    id: "pro",
    name: "Pro Cloud",
    shortName: "Pro",
    badge: "PRO CLOUD",
    badgeClass: "bg-blue-50 text-[#1a73e8] dark:bg-blue-950/60 dark:text-blue-300 border-blue-200 dark:border-blue-800",
    storageTotalGB: 2048.0, // 2 TB
    storageUsedGB: 124.5,
    storageUsedPercentage: 6,
    maxVideoQuality: "1080p & 4K HLS",
    allowedVideoQualities: ["1080p", "720p", "480p"],
    bedrockMonthlyDocs: 2500,
    bedrockTokensTotal: 500000,
    bedrockTokensUsed: 42800,
    rekognitionMonthlyScans: 5000,
    rekognitionScansUsed: 890,
    fargateComputeMonthlyMins: 180,
    fargateComputeUsedMins: 45,
    isEnterprise: false,
    infraTitle: "Dedicated S3 Multi-Region Storage",
    infraDesc: "Multi-region S3 replication with priority ARM64 Graviton3 transcoding workers and high-speed ingest.",
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    shortName: "Enterprise",
    badge: "ENTERPRISE VPC",
    badgeClass: "bg-purple-50 text-purple-700 dark:bg-purple-950/60 dark:text-purple-300 border-purple-200 dark:border-purple-800",
    storageTotalGB: 10000.0,
    isUnlimitedStorage: true,
    storageUsedGB: 1840.0,
    storageUsedPercentage: 18,
    maxVideoQuality: "4K Cinema & 1080p HLS",
    allowedVideoQualities: ["1080p", "720p", "480p"],
    bedrockMonthlyDocs: 50000,
    bedrockTokensTotal: 5000000,
    bedrockTokensUsed: 620000,
    rekognitionMonthlyScans: 100000,
    rekognitionScansUsed: 14200,
    fargateComputeMonthlyMins: 5000,
    fargateComputeUsedMins: 720,
    isEnterprise: true,
    infraTitle: "Customer-Dedicated AWS VPC",
    infraDesc: "Isolated VPC (vpc-0a89d71c89f2a4e1), BYOK KMS Encryption, and 24/7 dedicated solutions architect.",
  },
};

export const getPlanDetails = (planId = "free") => {
  return PLANS[planId] || PLANS.free;
};
